main: io.github.lazoyoung.endusereconomy.Main
name: EndUserEconomy
version: 1.0
api-version: 1.13
description: Use bank to convert your virtual money into real item in Minecraft.
author: LazoYoung
load: STARTUP
softdepend:
  - Vault
  - GemsEconomy

commands:
  usereco:
    usage: Type /eue to see help.
    aliases: [endeco, economy]
  bill:
    usage: Type /bill to see help.
    aliases: [coin]
  account:
    usage: Type /account to see help.
    aliases: [bank]