main: io.github.lazoyoung.Main
name: EndUserEconomy
version: 1.0
api-version: 1.13
description: Use bank to convert your virtual money into real item in Minecraft.
author: LazoYoung
load: STARTUP
softdepend:
- Vault

commands:
  economy:
    usage: Type /economy to see help.
    aliases: eco
  bill:
    usage: Type /bill to see help.
    aliases: [coin, papermoney]